import type { Metadata } from 'next';

import { mulish, oldStandardTT } from '@/lib/fonts';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${mulish.variable} ${oldStandardTT.variable}`}>
        {children}
      </body>
    </html>
  );
}
